services:
  - type: web
    name: backend
    env: node
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend &&  npm start
    rootDir: landingPageZarlenga
    envVars:
      - key: HOST
        value: localhost
      - key: PORT
        value: 4000
      - key: DATABASE
        value: app_mc
      - key: USER
        value: root
      - key: PASSWORD
        value: lindura010

    - type: web
      name: frontend
      env: node
      buildCommand: cd frontend && npm install && npm run build
      startCommand: cd frontend && npm run preview
      staticPublishPath: frontend/dist